name: MCP Server - Tests
  
on: 
  push:
    branches: ['main']
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
  workflow_dispatch:

jobs:
  test:
    name: Unit & Integration Tests
    runs-on: ubuntu-latest
    container: node:22.17-alpine
    
    steps:
      - uses: actions/checkout@v4
        
      # Test MCP server
      - name: Install MCP server dependencies
        working-directory: ./mcp-server
        run: npm ci
        
      - name: Run MCP server tests
        working-directory: ./mcp-server
        env:
          CENSUS_API_KEY: ${{ secrets.CENSUS_API_KEY }}
          NODE_ENV: test
        run: npm test